### ISSUE TITLE
Modify the sidebar for better compatibility and UX

### ISSUE THREAD

**Issue by Yuji-Itadorii** [NIT-KKR-Student-Support-System/NKSS-frontend#1]
When I click on the icons then the Sidebar expands which works fine, but when I click on the links related to icons then it should collapse.
Although it works fine on a big screen but on mobile user has to close the sidebar manually.

**Comment by Yuji-Itadorii** [comment]
hey @TheAlpha27, please assign this issue to me

**Comment by GetPsyched** [comment]
Hey, @Yuji-Itadorii, I've assigned this issue to you. Also, @TheAlpha27 is currently inactive. This repo is going to be taken forward by @techsavvyash instead.

**Comment by Yuji-Itadorii** [comment]
ok , Thanks

**Comment by Yuji-Itadorii** [comment]
hey, @techsavvyash I have created a pull request please review it and let me know if you find any issues with it.

**Comment by techsavvyash** [comment]
Sure! :+1:
